// <auto-generated />
using System;
using Klipp_StyleSalong.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Klipp_StyleSalong.Migrations
{
    [DbContext(typeof(SalonDbContext))]
    [Migration("20260202094519_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Klipp_StyleSalong.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Hairdresser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerName = "Sofia Larsson",
                            Date = new DateOnly(2026, 2, 10),
                            Hairdresser = "Anna",
                            PhoneNr = "0701234567",
                            Time = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CustomerName = "Johan Svensson",
                            Date = new DateOnly(2026, 2, 10),
                            Hairdresser = "Erik",
                            PhoneNr = "0739876543",
                            Time = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            CustomerName = "Elin Andersson",
                            Date = new DateOnly(2026, 2, 10),
                            Hairdresser = "Anna",
                            PhoneNr = "0725551234",
                            Time = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            CustomerName = "Mikael Johansson",
                            Date = new DateOnly(2026, 2, 11),
                            Hairdresser = "Erik",
                            PhoneNr = "0761122334",
                            Time = new TimeOnly(9, 30, 0)
                        },
                        new
                        {
                            Id = 5,
                            CustomerName = "Lisa Karlsson",
                            Date = new DateOnly(2026, 2, 11),
                            Hairdresser = "Anna",
                            PhoneNr = "0709988776",
                            Time = new TimeOnly(10, 30, 0)
                        },
                        new
                        {
                            Id = 6,
                            CustomerName = "Fredrik Nilsson",
                            Date = new DateOnly(2026, 2, 12),
                            Hairdresser = "Erik",
                            PhoneNr = "0736655443",
                            Time = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            CustomerName = "Emma Olsson",
                            Date = new DateOnly(2026, 2, 12),
                            Hairdresser = "Anna",
                            PhoneNr = "0723344556",
                            Time = new TimeOnly(14, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            CustomerName = "Patrik Lindberg",
                            Date = new DateOnly(2026, 2, 13),
                            Hairdresser = "Erik",
                            PhoneNr = "0707766554",
                            Time = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            CustomerName = "Johanna Berg",
                            Date = new DateOnly(2026, 2, 13),
                            Hairdresser = "Anna",
                            PhoneNr = "0732233445",
                            Time = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            CustomerName = "David Svensson",
                            Date = new DateOnly(2026, 2, 14),
                            Hairdresser = "Erik",
                            PhoneNr = "0728899001",
                            Time = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            CustomerName = "Hanna Svensson",
                            Date = new DateOnly(2026, 2, 15),
                            Hairdresser = "Erik",
                            PhoneNr = "0768990565",
                            Time = new TimeOnly(13, 0, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
